
import { PlanetData } from './types';

export const PLANETS: PlanetData[] = [
  {
    id: 'mercury',
    name: 'Mercúrio',
    tagline: 'O Pequeno Mensageiro',
    description: 'O planeta mais próximo do Sol e o menor do sistema solar.',
    distance: 10,
    radius: 0.8,
    color: '#8c8c8c',
    stats: {
      diameter: '4.879 km',
      mass: '3,285 × 10^23 kg',
      gravity: '3,7 m/s²',
      temp: '-173°C a 427°C',
      day: '58d 15h',
      year: '88 dias',
      moons: 0,
    },
    science: {
      atmosphere: 'Praticamente inexistente (Exosfera)',
      structure: 'Núcleo de ferro maciço (75% do raio)',
      pressure: 'Extremamente baixa',
      magneticField: 'Sim (1% da Terra)',
      curiosities: ['Superfície coberta de crateras', 'O planeta mais denso após a Terra'],
    },
    missions: [
      { name: 'Mariner 10', year: '1973', status: 'Encerrada', agency: 'NASA' },
      { name: 'MESSENGER', year: '2004', status: 'Sucesso', agency: 'NASA' },
      { name: 'BepiColombo', year: '2018', status: 'Ativa', agency: 'ESA/JAXA' },
    ]
  },
  {
    id: 'venus',
    name: 'Vênus',
    tagline: 'O Gêmeo Infernal',
    description: 'Frequentemente chamado de planeta irmão da Terra, mas com uma atmosfera mortal.',
    distance: 15,
    radius: 1.5,
    color: '#e3bb76',
    stats: {
      diameter: '12.104 km',
      mass: '4,867 × 10^24 kg',
      gravity: '8,87 m/s²',
      temp: '464°C (Média)',
      day: '243 dias',
      year: '225 dias',
      moons: 0,
    },
    science: {
      atmosphere: 'Densa (96% CO2), nuvens de ácido sulfúrico',
      structure: 'Núcleo de ferro, manto rochoso',
      pressure: '92 vezes a da Terra',
      magneticField: 'Não detectável',
      curiosities: ['Gira no sentido horário', 'O planeta mais quente do sistema solar', 'Vulcões ativos'],
    },
    missions: [
      { name: 'Venera 7', year: '1970', status: 'Sucesso', agency: 'URSS' },
      { name: 'Magellan', year: '1989', status: 'Encerrada', agency: 'NASA' },
      { name: 'Akatsuki', year: '2010', status: 'Ativa', agency: 'JAXA' },
    ]
  },
  {
    id: 'earth',
    name: 'Terra',
    tagline: 'O Pálido Ponto Azul',
    description: 'Nosso único lar conhecido, rico em água líquida e vida.',
    distance: 22,
    radius: 1.6,
    color: '#2b82c9',
    stats: {
      diameter: '12.742 km',
      mass: '5,972 × 10^24 kg',
      gravity: '9,8 m/s²',
      temp: '15°C (Média)',
      day: '24h',
      year: '365 dias',
      moons: 1,
    },
    science: {
      atmosphere: '78% Nitrogênio, 21% Oxigênio',
      structure: 'Núcleo interno sólido, manto, crosta tectônica',
      pressure: '1 atm (Nível do mar)',
      magneticField: 'Sim (Forte)',
      curiosities: ['Único planeta com água líquida na superfície', 'Protegido por um cinturão de radiação'],
    },
    missions: [
      { name: 'ISS', year: '1998', status: 'Ativa', agency: 'Global' },
      { name: 'Landsat 9', year: '2021', status: 'Ativa', agency: 'NASA' },
    ]
  },
  {
    id: 'mars',
    name: 'Marte',
    tagline: 'O Planeta Vermelho',
    description: 'O foco principal da busca por vida extraterrestre.',
    distance: 30,
    radius: 1.2,
    color: '#e27b58',
    stats: {
      diameter: '6.779 km',
      mass: '6,39 × 10^23 kg',
      gravity: '3,71 m/s²',
      temp: '-65°C (Média)',
      day: '24h 37m',
      year: '687 dias',
      moons: 2,
    },
    science: {
      atmosphere: 'Fina (95% CO2)',
      structure: 'Núcleo de ferro e enxofre, crosta espessa',
      pressure: '0,6% da Terra',
      magneticField: 'Vestigial (Remanescente)',
      curiosities: ['Maior vulcão: Olympus Mons', 'Possui o maior desfiladeiro: Valles Marineris'],
    },
    missions: [
      { name: 'Perseverance', year: '2020', status: 'Ativa', agency: 'NASA' },
      { name: 'Curiosity', year: '2011', status: 'Ativa', agency: 'NASA' },
      { name: 'Hope', year: '2020', status: 'Ativa', agency: 'UAE' },
    ]
  },
  {
    id: 'jupiter',
    name: 'Júpiter',
    tagline: 'O Rei dos Gigantes',
    description: 'O maior planeta, um gigante gasoso com uma massa duas vezes superior à de todos os outros planetas juntos.',
    distance: 45,
    radius: 4.0,
    color: '#d39c7e',
    stats: {
      diameter: '139.820 km',
      mass: '1,898 × 10^27 kg',
      gravity: '24,79 m/s²',
      temp: '-110°C (Média)',
      day: '9h 55m',
      year: '11,8 anos',
      moons: 95,
    },
    science: {
      atmosphere: 'Hidrogênio e Hélio',
      structure: 'Hidrogênio metálico líquido em volta do núcleo',
      pressure: 'Extrema (Milhões de vezes a terrestre)',
      magneticField: 'Sim (Mais forte do sistema solar)',
      curiosities: ['Grande Mancha Vermelha (Tempestade secular)', 'Possui anéis tênues'],
    },
    missions: [
      { name: 'Galileo', year: '1989', status: 'Encerrada', agency: 'NASA' },
      { name: 'Juno', year: '2011', status: 'Ativa', agency: 'NASA' },
      { name: 'JUICE', year: '2023', status: 'Ativa', agency: 'ESA' },
    ]
  },
  {
    id: 'saturn',
    name: 'Saturno',
    tagline: 'A Joia do Sistema Solar',
    description: 'Famoso por seu complexo e deslumbrante sistema de anéis.',
    distance: 60,
    radius: 3.5,
    color: '#c5ab6e',
    stats: {
      diameter: '116.460 km',
      mass: '5,683 × 10^26 kg',
      gravity: '10,44 m/s²',
      temp: '-140°C (Média)',
      day: '10h 42m',
      year: '29,4 anos',
      moons: 146,
    },
    science: {
      atmosphere: '75% Hidrogênio, 25% Hélio',
      structure: 'Núcleo rochoso, envelope de hidrogênio metálico',
      pressure: 'Altíssima',
      magneticField: 'Sim (Ligeiramente mais fraco que a Terra)',
      curiosities: ['Menos denso que a água', 'Anéis compostos por gelo e poeira'],
    },
    missions: [
      { name: 'Voyager 1', year: '1977', status: 'Ativa', agency: 'NASA' },
      { name: 'Cassini-Huygens', year: '1997', status: 'Sucesso', agency: 'NASA/ESA' },
    ]
  },
  {
    id: 'uranus',
    name: 'Urano',
    tagline: 'O Gigante de Gelo',
    description: 'Um mundo azul-esverdeado gelado que gira de lado.',
    distance: 75,
    radius: 2.2,
    color: '#bbe1e4',
    stats: {
      diameter: '50.724 km',
      mass: '8,681 × 10^25 kg',
      gravity: '8,69 m/s²',
      temp: '-195°C (Média)',
      day: '17h 14m',
      year: '84 anos',
      moons: 27,
    },
    science: {
      atmosphere: 'Hidrogênio, Hélio, Metano',
      structure: 'Manto de gelos fluidos (água, amônia, metano)',
      pressure: 'Alta',
      magneticField: 'Sim (Inclinado 59 graus)',
      curiosities: ['Eixo de rotação quase paralelo à órbita', 'Possui 13 anéis conhecidos'],
    },
    missions: [
      { name: 'Voyager 2', year: '1977', status: 'Ativa', agency: 'NASA' },
    ]
  },
  {
    id: 'neptune',
    name: 'Netuno',
    tagline: 'O Mundo Ventoso',
    description: 'O planeta mais distante, assolado pelos ventos mais rápidos do sistema solar.',
    distance: 90,
    radius: 2.1,
    color: '#6081ff',
    stats: {
      diameter: '49.244 km',
      mass: '1,024 × 10^26 kg',
      gravity: '11,15 m/s²',
      temp: '-201°C (Média)',
      day: '16h 6m',
      year: '165 anos',
      moons: 14,
    },
    science: {
      atmosphere: 'Hidrogênio, Hélio, Metano',
      structure: 'Núcleo rochoso envolto por gelos comprimidos',
      pressure: 'Alta',
      magneticField: 'Sim (Deslocado do centro)',
      curiosities: ['Ventos de 2.100 km/h', 'Primeiro planeta descoberto por cálculo matemático'],
    },
    missions: [
      { name: 'Voyager 2', year: '1977', status: 'Ativa', agency: 'NASA' },
    ]
  }
];
